"""Create schemas

Revision ID: 12d8ba82ee0e
Revises: None
Create Date: 2014-12-17 09:47:29.600008

"""

# revision identifiers, used by Alembic.
revision = '12d8ba82ee0e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=1200), nullable=True),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=200), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('birthyear', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('facebook', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['monkey.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['idea_status.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkey.id'], ondelete='CASCADE')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ondelete='CASCADE')
    )
    op.create_table('join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_request')
    op.drop_table('fields')
    op.drop_table('suggestion')
    op.drop_table('members')
    op.drop_table('idea')
    op.drop_table('monkey')
    op.drop_table('profession')
    op.drop_table('field')
    op.drop_table('idea_status')
    ### end Alembic commands ###
