"""empty message

Revision ID: 282cc57221da
Revises: 41f86a5c7465
Create Date: 2014-12-01 19:47:41.495497

"""

# revision identifiers, used by Alembic.
revision = '282cc57221da'
down_revision = '41f86a5c7465'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
