"""empty message

Revision ID: 2eab03325f94
Revises: 31ea054d32f7
Create Date: 2014-10-16 17:52:14.198245

"""

# revision identifiers, used by Alembic.
revision = '2eab03325f94'
down_revision = '31ea054d32f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammate_request', sa.Column('message', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teammate_request', 'message')
    ### end Alembic commands ###
