"""empty message

Revision ID: 31ea054d32f7
Revises: None
Create Date: 2014-10-16 17:48:19.346065

"""

# revision identifiers, used by Alembic.
revision = '31ea054d32f7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
