"""empty message

Revision ID: 32a963461743
Revises: None
Create Date: 2014-12-01 00:43:23.397971

"""

# revision identifiers, used by Alembic.
revision = '32a963461743'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
