"""empty message

Revision ID: 41f86a5c7465
Revises: b1a6e7286bf
Create Date: 2014-12-01 19:10:35.526410

"""

# revision identifiers, used by Alembic.
revision = '41f86a5c7465'
down_revision = 'b1a6e7286bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkey', sa.Column('password', sa.String(length=1200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monkey', 'password')
    ### end Alembic commands ###
