"""empty message

Revision ID: 566164fd8a79
Revises: 2eab03325f94
Create Date: 2014-10-18 18:12:40.697503

"""

# revision identifiers, used by Alembic.
revision = '566164fd8a79'
down_revision = '2eab03325f94'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teammate_request')
    op.add_column(u'idea', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column(u'monkey', sa.Column('is_busy', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'monkey', 'is_busy')
    op.drop_column(u'idea', 'status_id')
    op.create_table('teammate_request',
    sa.Column('id', sa.INTEGER(), server_default="nextval('teammate_request_id_seq'::regclass)", nullable=False),
    sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_id'], [u'monkey.id'], name=u'teammate_request_from_id_fkey'),
    sa.ForeignKeyConstraint(['idea_id'], [u'idea.id'], name=u'teammate_request_idea_id_fkey'),
    sa.ForeignKeyConstraint(['to_id'], [u'monkey.id'], name=u'teammate_request_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'teammate_request_pkey')
    )
    op.drop_table('join_request')
    op.drop_table('suggestion')
    op.drop_table('idea_status')
    ### end Alembic commands ###
