"""empty message

Revision ID: b1a6e7286bf
Revises: 32a963461743
Create Date: 2014-12-01 19:09:41.401914

"""

# revision identifiers, used by Alembic.
revision = 'b1a6e7286bf'
down_revision = '32a963461743'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monkey', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkey', sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    ### end Alembic commands ###
