"""empty message

Revision ID: d25a6bf439c
Revises: 566164fd8a79
Create Date: 2014-10-19 20:33:00.321860

"""

# revision identifiers, used by Alembic.
revision = 'd25a6bf439c'
down_revision = '566164fd8a79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkey', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.drop_column('monkey', 'is_busy')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkey', sa.Column('is_busy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('monkey', 'is_public')
    ### end Alembic commands ###
